// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWDnOtbvy4P9i2aHtAxpkxbEfWR1yTseE',
    appId: '1:513381611469:web:ee3d574a1fe72ecfc87684',
    messagingSenderId: '513381611469',
    projectId: 'millionsfirebase',
    authDomain: 'millionsfirebase.firebaseapp.com',
    storageBucket: 'millionsfirebase.firebasestorage.app',
    measurementId: 'G-CD603V78YP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmwPVJ2H1VTkVzEf3aVKAyy_6ePELb4hQ',
    appId: '1:513381611469:android:77a43f146db2ffe9c87684',
    messagingSenderId: '513381611469',
    projectId: 'millionsfirebase',
    storageBucket: 'millionsfirebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHDURXEfLimxI28xBstzKA_qIsA4xK988',
    appId: '1:513381611469:ios:f4a5335865c5075cc87684',
    messagingSenderId: '513381611469',
    projectId: 'millionsfirebase',
    storageBucket: 'millionsfirebase.firebasestorage.app',
    iosBundleId: 'com.example.millions',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHDURXEfLimxI28xBstzKA_qIsA4xK988',
    appId: '1:513381611469:ios:f4a5335865c5075cc87684',
    messagingSenderId: '513381611469',
    projectId: 'millionsfirebase',
    storageBucket: 'millionsfirebase.firebasestorage.app',
    iosBundleId: 'com.example.millions',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWDnOtbvy4P9i2aHtAxpkxbEfWR1yTseE',
    appId: '1:513381611469:web:cfcef7b533976dbac87684',
    messagingSenderId: '513381611469',
    projectId: 'millionsfirebase',
    authDomain: 'millionsfirebase.firebaseapp.com',
    storageBucket: 'millionsfirebase.firebasestorage.app',
    measurementId: 'G-VGCR6YSZEG',
  );
}
