name: millions
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider:
  firebase_core: ^3.10.1
  cloud_firestore: ^5.6.6
  firebase_auth: ^5.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  fonts:
    - family: Charm
      fonts:
        - asset: fonts/Charm-Regular.ttf
    - family: OutfitLight
      fonts:
        - asset: fonts/Outfit-Light.ttf

  uses-material-design: true

